vars:
  - file: ./vars/{{ args.env_type }}.yml

deployments:
  - path: namespaces
  - barrier: true
  - include: third-party
  - include: services

commonLabels:
  examples.kluctl.io/deployment-project: "microservices-demo"
  examples.kluctl.io/deployment-target: "{{ target.name }}"

overrideNamespace: ms-demo-{{ target.name }}
