clusters:
  - project:
      url: git@github.com:kluctl/kluctl-examples-external-clusters.git
      subDir: clusters

deployment:
  project:
    url: git@github.com:kluctl/kluctl-examples-external-deployments.git
    ref: main
    subDir: simple

targets:
  - name: simple-with-external-repos
    cluster: kind
    args:
      environment: simple-with-external-repos
