clusters:
  project:
    url: https://github.com/AljoschaP/kluctl-external-clusters
    subdir: clusters

deployment:
  project:
    url: https://github.com/AljoschaP/kluctl-external-deployments
    subdir: simple
    ref: main

targets:
  - name: dev-external
    cluster: kind
    args:
      environment: dev-external
